# Generated by Django 4.1.2 on 2022-10-25 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_dokter', models.CharField(max_length=10, unique=True)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.CharField(max_length=10)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JenisKelamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.CharField(max_length=10)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_rm', models.CharField(max_length=10)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nik', models.CharField(blank=True, max_length=20, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('telepon', models.CharField(max_length=15)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True, null=True)),
                ('jenis_kelamin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasien', to='beta_rini_api.jeniskelamin')),
            ],
            options={
                'unique_together': {('nomor_rm', 'username')},
            },
        ),
        migrations.CreateModel(
            name='Poli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.CharField(max_length=20)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spesialis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.CharField(max_length=50)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_registrasi', models.CharField(max_length=30, unique=True)),
                ('tanggal_registrasi', models.DateField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True, null=True)),
                ('dokter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendaftaran', to='beta_rini_api.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran', to='beta_rini_api.pasien')),
                ('poli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendaftaran', to='beta_rini_api.poli')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_mulai', models.TimeField()),
                ('waktu_selesai', models.TimeField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True, null=True)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='beta_rini_api.dokter')),
                ('hari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='beta_rini_api.hari')),
            ],
        ),
        migrations.AddField(
            model_name='dokter',
            name='jenis_kelamin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokter', to='beta_rini_api.jeniskelamin'),
        ),
        migrations.AddField(
            model_name='dokter',
            name='spesialis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokter', to='beta_rini_api.spesialis'),
        ),
    ]
